In [1]:
import torch
print(torch.__version__)

2.13.0+cpu


In [2]:
# Tensors are the building blocks of PyTorch. They are similar to NumPy arrays,  but can also be used on a GPU
# to accelerate computing. they can learn from data and can be used to build neural networks.

import torch
x=torch.tensor([1, 2, 3]) # 1D tensor
print(x)

tensor([1, 2, 3])


In [3]:
y=torch.tensor([[1, 2, 3], [4, 5, 6]]) # 2D tensor
print(y)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [4]:
z=torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) # 3D tensor
print(z)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])


In [ ]:
a=torch.zeros((2, 3)) # 2D tensor of zeros (rows=2, columns=3)
print(a)

b=torch.ones((2, 3)) # 2D tensor of ones (rows=2, columns=3)
print(b)

c=torch.rand((2, 3)) # 2D tensor of random numbers (rows=2, columns=3)
print(c)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3962, 0.7793, 0.6201],
        [0.3877, 0.7754, 0.2120]])
torch.Size([2, 3])


In [ ]:
# Shape and indexing of tensors

d = torch.tensor([1, 2, 3, 4, 5]) # 1D tensor
print(d)
print(d.shape)

e = torch.tensor([[1, 2, 3], [4, 5, 6]]) # 2D tensor
print(e)
print(e.shape)

# Indexing
print(d[0]) # first element
print(e[0]) # first row
print(e[0, 0]) # first row, first column

In [16]:
#Operations on tensors
f = torch.tensor([1, 2, 3])
g = torch.tensor([4, 5, 6])

h = f + g # element-wise addition
i = f * g # element-wise multiplication
print(h,"\n",i) 
#print(f.mean()) # mean of tensor f
print(f.sum()) # sum of tensor f
print(f.max()) # maximum value of tensor f
print(f.min()) # minimum value of tensor f
print(f.argmax()) # index of maximum value of tensor f
print(f.argmin()) # index of minimum value of tensor f
print(f.reshape(3, 1)) # reshape tensor f to 3 rows and 1 column
print(f.view(3, 1)) # view tensor f as 3 rows and 1 column
print(f.unsqueeze(0)) # add a dimension at the 0th index
print(f.unsqueeze(1)) # add a dimension at the 1st index
print(f.squeeze()) # remove dimensions of size 1
print(f.transpose(0,-1)) # transpose tensor f means to swap the dimensions of a tensor. The transpose function takes a tuple of integers as input, which specifies the new order of dimensions. For example, if we have a tensor of shape (2, 3), and we want to transpose it to shape (3, 2), we can use f.transpose(0, 1). This will swap the first and second dimensions of the tensor.
#print(f.permute(1, 0)) # permute dimensions of tensor f permute means to change the order of dimensions of a tensor. The permute function takes a tuple of integers as input, which specifies the new order of dimensions. For example, if we have a tensor of shape (2, 3, 4), and we want to permute it to shape (4, 2, 3), we can use f.permute(2, 0, 1). This will move the last dimension to the first position, the first dimension to the second position, and the second dimension to the last position.
print(f.clone()) # create a copy of tensor f
print(f.detach()) # create a tensor that shares storage with f but does not require gradients
print(f.requires_grad) # check if tensor f requires gradients
#print(f.requires_grad_()) # set requires_grad to True for tensor f
print(f.grad) # check the gradient of tensor f
#print(f.backward()) # compute the gradient of tensor f
print(f+10) # add 10 to each element of tensor f
print(f*10) # multiply each element of tensor f by 10

tensor([5, 7, 9]) 
 tensor([ 4, 10, 18])
tensor(6)
tensor(3)
tensor(1)
tensor(2)
tensor(0)
tensor([[1],
        [2],
        [3]])
tensor([[1],
        [2],
        [3]])
tensor([[1, 2, 3]])
tensor([[1],
        [2],
        [3]])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])
False
None
tensor([11, 12, 13])
tensor([10, 20, 30])


In [ ]:
# Linear regression using PyTorch
one=torch.tensor([1., 2., 3.])
two=torch.tensor([4., 5., 6.])

# Define the model parameters (weights and bias)
w=torch.tensor((0.0)) 
b=torch.tensor((0.0))


y_pred=one*w+b # predicted values using the linear regression model
loss=torch.mean((y_pred-two)**2)

print("Predicted values:", y_pred)
print("Actual values:", two)
print("Loss:", loss)

Predicted values: tensor([0., 0., 0.])
Actual values: tensor([4., 5., 6.])
Loss: tensor(25.6667)
